### PR TITLE
Refactor face normals detection

### PR DESCRIPTION
**Pull request by dy**
Because we should not use `gl_FrontFacing` - it is not supported well across devices.
Related to http://stackoverflow.com/questions/24375171/is-there-a-reliable-alternative-to-gl-frontfacing-in-a-fragment-shader.
Should fix https://github.com/plotly/plotly.js/issues/1368

### CODE REVIEW

**Comment by dfcreative** [comment]
@etpinard could you please test this on the images set? There should not be regression but who knows

**Comment by etpinard** [comment]
@dfcreative here are the new baselines:

https://github.com/plotly/plotly.js/compare/mesh3d-face-normals

**Comment by dfcreative** [comment]
@etpinard hmm, seems that `OES_standard_derivatives` extension is not supported on Linux or something. How do you generate these baselines? I cannot reproduce these wrong images neither on OSX nor win.
Can you please run [this website](http://prideout.net/recipes/ExtensionViewer.html) on the machine where you generate baselines and check that `OES_standard_derivatives` is supported?

**Comment by etpinard** [comment]
> seems that OES_standard_derivatives extension is not supported on Linu

Oh. That's going to be a problem.

> How do you generate these baselines?

By running [`npm run baseline -- <mock>`](https://github.com/plotly/plotly.js/blob/master/test/image/make_baseline.js) on my T450s ThinkPad with Ubuntu 16.04

> Can you please run this website on the machine where you generate baselines and check that OES_standard_derivatives is supported?

I get

image

**Comment by etpinard** [comment]
At first, I thought this could be a nw.js-only issue, but no. Even in Chrome 56, Snowden looks very shaded:

image

**Comment by dfcreative** [comment]
@etpinard can you try 23fa66d with increased precision? Even my iPhone renders that ok

**Comment by etpinard** [comment]
> can you try 23fa66d with increased precision?

Same result:

image

**Comment by etpinard** [comment]
@dfcreative I'm not sure what happened 2 days ago. I just tried generating the baselines again and Snowden is a lot better now:

image

see https://github.com/plotly/plotly.js/compare/mesh3d-face-normals for more diffs.

----

There's clearly a diff though between the old and the new baselines. Can you confirm that the new baselines look they way they should?

**Comment by etpinard** [comment]
with the latest patch, even CI has no problem generating the meshes 

image

https://circleci.com/gh/plotly/plotly.js/3598?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

:tada: :tada: :tada:

**Comment by dfcreative** [comment]
@etpinard I reverted normals to minimize breakage of the most baselines. In particular, only two snowden images are broken due to inverse vertex order in polygons.

**Comment by jackparmer** [comment]
Can we merge this? No customers are using `mesh3d`. _We_ barely even know how to use it :) `mesh3d` is giving different results on different Macbooks however, and I'm told this PR _might_ fix that.

**Comment by etpinard** [comment]
We should try some of empet's graphs before.

**Comment by jackparmer** [comment]
> We should try some of empet's graphs before.

Good idea. Maybe easiest is to deploy this to stage? I found these `mesh3d` plots on stage: 

https://stage.plot.ly/~empet/14328/
https://stage.plot.ly/~empet/13734/
https://stage.plot.ly/~RPlotBot/3008
https://stage.plot.ly/~chelsea_lyn/12064
https://stage.plot.ly/~empet/14151/

These brain ones in particular demonstrates this issues:
https://stage.plot.ly/~empet/14234/
https://stage.plot.ly/~empet/14232/

**Pull request merged**
